services:
  postgres:
    image: postgres:16.2
    container_name: pgcontainer
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
